// ============================================================
// Catálogos SUGEF / SICVECA — Módulo 1
// ============================================================

export const ACTIVIDADES_APNFD = [
  { nombre: 'Metales y Piedras Preciosas',    clase_dato: 40, archivo: 4001, monto_min_usd: 15000 },
  { nombre: 'Casas de Empeño',                clase_dato: 41, archivo: 4101, monto_min_usd: 10000 },
  { nombre: 'Organizaciones Sin Fines Lucro', clase_dato: 42, archivo: 4201, monto_min_usd: 1000  },
  { nombre: 'Casinos',                        clase_dato: 43, archivo: 4301, monto_min_usd: 3000  },
  { nombre: 'Administración de Dinero',       clase_dato: 44, archivo: 4401, monto_min_usd: 10000 },
  { nombre: 'Remesas y Transferencias',       clase_dato: 45, archivo: 4501, monto_min_usd: 1000  },
  { nombre: 'Emisión/Operación Tarjetas',     clase_dato: 46, archivo: 4601, monto_min_usd: 10000 },
  { nombre: 'Facilidades Crediticias',        clase_dato: 47, archivo: 4701, monto_min_usd: 10000 },
  { nombre: 'Servicios Fiduciarios',          clase_dato: 48, archivo: 4801, monto_min_usd: 10000 },
  { nombre: 'Bienes Inmuebles',               clase_dato: 49, archivo: 4901, monto_min_usd: 10000 },
]

export const TIPO_IDENTIFICACION = [
  { codigo: 1,  descripcion: 'Persona física nacional' },
  { codigo: 2,  descripcion: 'Persona jurídica nacional' },
  { codigo: 3,  descripcion: 'Extranjero residente (DIMEX)' },
  { codigo: 4,  descripcion: 'Entidad financiera extranjera' },
  { codigo: 5,  descripcion: 'Otra persona extranjera (pasaporte)' },
  { codigo: 6,  descripcion: 'Empresa extranjera no financiera' },
  { codigo: 13, descripcion: 'Fideicomiso' },
]

export const TIPO_REPORTE = [
  { codigo: 1, descripcion: 'Efectivo' },
  { codigo: 2, descripcion: 'APNFD (otros medios de pago)' },
  { codigo: 3, descripcion: 'Efectivo y otros medios de pago' },
]

export const TIPO_OPERACION = [
  { codigo: 1, descripcion: 'Operación única' },
  { codigo: 2, descripcion: 'Operación múltiple' },
]

export const TIPO_MOVIMIENTO = [
  { codigo: 1, descripcion: 'Ingreso (cliente paga a la entidad)' },
  { codigo: 2, descripcion: 'Salida (entidad desembolsa al cliente)' },
  { codigo: 3, descripcion: 'Ingreso/Salida (solo Casinos)' },
]

export const TIPO_MONEDA = [
  { codigo: 1, descripcion: 'Colón (CRC)', indicador: 'N' },
  { codigo: 2, descripcion: 'Dólar (USD)', indicador: 'E' },
  { codigo: 3, descripcion: 'Euro (EUR)',  indicador: 'E' },
  { codigo: 4, descripcion: 'Otra moneda', indicador: 'E' },
]

export const TIPO_CARGA = [
  { codigo: 1, descripcion: 'Carga nueva' },
  { codigo: 2, descripcion: 'Prórroga' },
  { codigo: 3, descripcion: 'Reenvío' },
  { codigo: 4, descripcion: 'Cambio' },
]

export const TIPO_SUJETO = [
  { tipo: 'I',   meses: 2, descripcion: 'Tipo I — Reporte cada 2 meses' },
  { tipo: 'II',  meses: 3, descripcion: 'Tipo II — Reporte cada 3 meses' },
  { tipo: 'III', meses: 4, descripcion: 'Tipo III — Reporte cada 4 meses' },
]

// Tipos de Ingreso por ClaseDato
export const TIPOS_INGRESO = [
  { codigo: 0,  descripcion: 'No aplica',                         clases: [0,1,2,3,4,5,6,7,8,9,10] },
  { codigo: 1,  descripcion: 'Ventas',                             clases: [1] },
  { codigo: 2,  descripcion: 'Exportación',                        clases: [1] },
  { codigo: 3,  descripcion: 'Venta de artículos',                 clases: [2] },
  { codigo: 4,  descripcion: 'Venta de joyas',                     clases: [2] },
  { codigo: 5,  descripcion: 'Interés',                            clases: [2] },
  { codigo: 6,  descripcion: 'Cancelación de contrato de empeño',  clases: [2] },
  { codigo: 7,  descripcion: 'Abono',                              clases: [2] },
  { codigo: 8,  descripcion: 'Educación',                          clases: [3] },
  { codigo: 9,  descripcion: 'Vivienda',                           clases: [3] },
  { codigo: 10, descripcion: 'Emprendedurismo',                    clases: [3] },
  { codigo: 11, descripcion: 'Salud',                              clases: [3] },
  { codigo: 12, descripcion: 'Religioso',                          clases: [3] },
  { codigo: 13, descripcion: 'Político',                           clases: [3] },
  { codigo: 14, descripcion: 'Deportes',                           clases: [3] },
  { codigo: 15, descripcion: 'Desarrollo urbano',                  clases: [3] },
  { codigo: 16, descripcion: 'Alimentación',                       clases: [3] },
  { codigo: 17, descripcion: 'Ambiental',                          clases: [3] },
  { codigo: 18, descripcion: 'Vida silvestre',                     clases: [3] },
  { codigo: 19, descripcion: 'Niñez y adolescencia',               clases: [3] },
  { codigo: 20, descripcion: 'Farmacodependencias',                clases: [3] },
  { codigo: 21, descripcion: 'Adulto mayor',                       clases: [3] },
  { codigo: 22, descripcion: 'Venta de fichas',                    clases: [4] },
  { codigo: 23, descripcion: 'Ingreso en máquinas (efectivo)',     clases: [4] },
  { codigo: 24, descripcion: 'Monto administrado',                 clases: [5] },
  { codigo: 25, descripcion: 'Comisiones por administración',      clases: [5] },
  { codigo: 26, descripcion: 'Inversión',                          clases: [5] },
  { codigo: 27, descripcion: 'Remesa recibida',                    clases: [6] },
  { codigo: 28, descripcion: 'Op. sistemática y sustancial recibida', clases: [6] },
  { codigo: 29, descripcion: 'Venta',                              clases: [7] },
  { codigo: 30, descripcion: 'Contrato de administración',         clases: [7] },
  { codigo: 31, descripcion: 'Ingreso por emisión',                clases: [7] },
  { codigo: 32, descripcion: 'Pago de contado cliente',            clases: [7] },
  { codigo: 33, descripcion: 'Pago mínimo cliente',                clases: [7] },
  { codigo: 34, descripcion: 'Ingreso por procesamiento',          clases: [7] },
  { codigo: 35, descripcion: 'Comisión por servicios',             clases: [7] },
  { codigo: 36, descripcion: 'Pago otro monto',                    clases: [7] },
  { codigo: 37, descripcion: 'Pago intereses',                     clases: [8] },
  { codigo: 38, descripcion: 'Pago cuota',                         clases: [8] },
  { codigo: 39, descripcion: 'Pago de principal',                  clases: [8] },
  { codigo: 40, descripcion: 'Cancelación anticipada',             clases: [8] },
  { codigo: 41, descripcion: 'Abono extraordinario',               clases: [8] },
  { codigo: 42, descripcion: 'Gastos de formalización',            clases: [8] },
  { codigo: 43, descripcion: 'Comisión de formalización',          clases: [8] },
  { codigo: 44, descripcion: 'Fideicomiso',                        clases: [9] },
  { codigo: 45, descripcion: 'Aporte inicial al fideicomiso',      clases: [9] },
  { codigo: 46, descripcion: 'Aporte extraordinario',              clases: [9] },
  { codigo: 47, descripcion: 'Comisiones',                         clases: [9] },
  { codigo: 48, descripcion: 'Venta',                              clases: [10] },
  { codigo: 49, descripcion: 'Comisión',                           clases: [10] },
  { codigo: 50, descripcion: 'Pago de prima',                      clases: [10] },
  { codigo: 51, descripcion: 'Pago parcial',                       clases: [10] },
  { codigo: 52, descripcion: 'Pago total',                         clases: [10] },
  { codigo: 53, descripcion: 'Colocación de fichas',               clases: [4] },
  { codigo: 54, descripcion: 'Colocación de tiquetes',             clases: [4] },
  { codigo: 55, descripcion: 'Ingreso en máquina (efectivo)',      clases: [4] },
  { codigo: 56, descripcion: 'Prima',                              clases: [8] },
]

// Tipos de Salida por ClaseDato
export const TIPOS_SALIDA = [
  { codigo: 0,  descripcion: 'No aplica',                               clases: [0,1,2,3,4,5,6,7,8,9,10] },
  { codigo: 1,  descripcion: 'Importación',                             clases: [1] },
  { codigo: 2,  descripcion: 'Compra de insumos',                       clases: [1] },
  { codigo: 3,  descripcion: 'Compra de artículos',                     clases: [2] },
  { codigo: 4,  descripcion: 'Compra de joyas',                         clases: [2] },
  { codigo: 5,  descripcion: 'Educación',                               clases: [3] },
  { codigo: 6,  descripcion: 'Vivienda',                                clases: [3] },
  { codigo: 7,  descripcion: 'Emprendedurismo',                         clases: [3] },
  { codigo: 8,  descripcion: 'Salud',                                   clases: [3] },
  { codigo: 9,  descripcion: 'Religioso',                               clases: [3] },
  { codigo: 10, descripcion: 'Político',                                clases: [3] },
  { codigo: 11, descripcion: 'Deportes',                                clases: [3] },
  { codigo: 12, descripcion: 'Desarrollo urbano',                       clases: [3] },
  { codigo: 13, descripcion: 'Alimentación',                            clases: [3] },
  { codigo: 14, descripcion: 'Ambiental',                               clases: [3] },
  { codigo: 15, descripcion: 'Vida silvestre',                          clases: [3] },
  { codigo: 16, descripcion: 'Niñez y adolescencia',                    clases: [3] },
  { codigo: 17, descripcion: 'Farmacodependencias',                     clases: [3] },
  { codigo: 18, descripcion: 'Adulto mayor',                            clases: [3] },
  { codigo: 19, descripcion: 'Canje de fichas',                         clases: [4] },
  { codigo: 20, descripcion: 'Pago Premio Máquinas',                    clases: [4] },
  { codigo: 21, descripcion: 'Pago Premio Mesas',                       clases: [4] },
  { codigo: 22, descripcion: 'Devolución de fondos',                    clases: [5] },
  { codigo: 23, descripcion: 'Inversión',                               clases: [5] },
  { codigo: 24, descripcion: 'Liquidación de contrato parcial',         clases: [5] },
  { codigo: 25, descripcion: 'Liquidación de contrato total',           clases: [5] },
  { codigo: 26, descripcion: 'Remesa pagada exterior',                  clases: [6] },
  { codigo: 27, descripcion: 'Remesa pagada local',                     clases: [6] },
  { codigo: 28, descripcion: 'Op. sistemática y sustancial pagada ext', clases: [6] },
  { codigo: 29, descripcion: 'Op. sistemática y sustancial pagada loc', clases: [6] },
  { codigo: 30, descripcion: 'Adelanto efectivo',                       clases: [7] },
  { codigo: 31, descripcion: 'Retiro cajero automático',                clases: [7] },
  { codigo: 32, descripcion: 'Devolución saldo a favor',                clases: [7] },
  { codigo: 33, descripcion: 'Desembolso crédito',                      clases: [8] },
  { codigo: 34, descripcion: 'Reintegro por saldo a favor del cliente', clases: [8] },
  { codigo: 35, descripcion: 'Retiros',                                 clases: [9] },
  { codigo: 36, descripcion: 'Cancelación o liquidación fideicomiso',   clases: [9] },
  { codigo: 37, descripcion: 'Reintegro o devolución',                  clases: [9] },
  { codigo: 38, descripcion: 'Compras',                                 clases: [10] },
  { codigo: 39, descripcion: 'Pago prima',                              clases: [10] },
  { codigo: 40, descripcion: 'Pago parcial',                            clases: [10] },
  { codigo: 41, descripcion: 'Pago comisión',                           clases: [10] },
  { codigo: 42, descripcion: 'Pago total',                              clases: [10] },
  { codigo: 43, descripcion: 'Canje de tiquetes',                       clases: [4] },
  { codigo: 44, descripcion: 'Empeño',                                  clases: [2] },
]

// Catálogo activo SUGEF SICVECA clase 47 — código 6 no está activo en SUGEF
export const MOTIVO_CREDITO = [
  { codigo: 0, descripcion: 'N/A' },
  { codigo: 1, descripcion: 'Crédito personal' },
  { codigo: 2, descripcion: 'Crédito vivienda' },
  { codigo: 3, descripcion: 'Crédito consumo' },
  { codigo: 4, descripcion: 'Crédito vehículo' },
  { codigo: 5, descripcion: 'Crédito salud' },
  { codigo: 7, descripcion: 'Crédito empresarial' },
  { codigo: 8, descripcion: 'Servicios exequiales' },
]

// Obtener tipos de ingreso filtrados por clase de actividad (0-indexed, clase_dato - 40)
// Etiqueta para "clientes" según actividad del sujeto obligado
// clase_dato 42 = Organizaciones Sin Fines de Lucro → donantes/beneficiarios
export function getEtiquetaCliente(tenant, plural = true) {
  if (!tenant) return plural ? 'clientes' : 'cliente'
  const clase = Number(tenant.clase_dato)
  if (clase === 42) return plural ? 'donantes / beneficiarios' : 'donante / beneficiario'
  return plural ? 'clientes' : 'cliente'
}

export function getTiposIngreso(claseDato) {
  const claseIdx = claseDato - 39 // convierte a índice 1-10
  return TIPOS_INGRESO.filter(t => t.clases.includes(0) || t.clases.includes(claseIdx))
}

export function getTiposSalida(claseDato) {
  const claseIdx = claseDato - 39
  return TIPOS_SALIDA.filter(t => t.clases.includes(0) || t.clases.includes(claseIdx))
}

// ─── Catálogo de PAÍS (tabla PAIS del descriptivo SUGEF, ISO alpha-2) ──────────
// Se usa en los campos de ubicación/país de recursos que exige SICVECA para casi
// todas las actividades (todas menos Facilidades Crediticias 47). El código de 2
// letras es lo que valida SICVECA; el nombre es solo para mostrar en el selector.
export const PAISES = [
  { codigo: 'AF', nombre: 'Afganistán' },
  { codigo: 'AL', nombre: 'Albania' },
  { codigo: 'DE', nombre: 'Alemania' },
  { codigo: 'AD', nombre: 'Andorra' },
  { codigo: 'AO', nombre: 'Angola' },
  { codigo: 'AI', nombre: 'Anguila' },
  { codigo: 'AQ', nombre: 'Antártida' },
  { codigo: 'AG', nombre: 'Antigua y Barbuda' },
  { codigo: 'AN', nombre: 'Antillas Holandesas' },
  { codigo: 'AX', nombre: 'Apátrida - sin nacionalidad' },
  { codigo: 'SA', nombre: 'Arabia Saudita' },
  { codigo: 'DZ', nombre: 'Argelia' },
  { codigo: 'AR', nombre: 'Argentina' },
  { codigo: 'AM', nombre: 'Armenia' },
  { codigo: 'AW', nombre: 'Aruba' },
  { codigo: 'AU', nombre: 'Australia' },
  { codigo: 'AT', nombre: 'Austria' },
  { codigo: 'AZ', nombre: 'Azerbaiyán' },
  { codigo: 'BS', nombre: 'Bahamas' },
  { codigo: 'BH', nombre: 'Bahréin' },
  { codigo: 'BD', nombre: 'Bangladesh' },
  { codigo: 'BB', nombre: 'Barbados' },
  { codigo: 'BE', nombre: 'Bélgica' },
  { codigo: 'BZ', nombre: 'Belice' },
  { codigo: 'BJ', nombre: 'Benin' },
  { codigo: 'BM', nombre: 'Bermuda' },
  { codigo: 'BY', nombre: 'Bielorrusia' },
  { codigo: 'BO', nombre: 'Bolivia' },
  { codigo: 'BQ', nombre: 'Bonaire, San Eustaquio y Saba' },
  { codigo: 'BA', nombre: 'Bosnia y Herzegovina' },
  { codigo: 'BW', nombre: 'Botsuana' },
  { codigo: 'BR', nombre: 'Brasil' },
  { codigo: 'BN', nombre: 'Brunéi Darussalam' },
  { codigo: 'BG', nombre: 'Bulgaria' },
  { codigo: 'BF', nombre: 'Burkina Faso' },
  { codigo: 'BI', nombre: 'Burundi' },
  { codigo: 'BT', nombre: 'Bután' },
  { codigo: 'CV', nombre: 'Cabo Verde' },
  { codigo: 'KH', nombre: 'Camboya' },
  { codigo: 'CM', nombre: 'Camerún' },
  { codigo: 'CA', nombre: 'Canadá' },
  { codigo: 'QA', nombre: 'Catar' },
  { codigo: 'TD', nombre: 'Chad' },
  { codigo: 'CL', nombre: 'Chile' },
  { codigo: 'CN', nombre: 'China' },
  { codigo: 'CY', nombre: 'Chipre' },
  { codigo: 'CO', nombre: 'Colombia' },
  { codigo: 'KM', nombre: 'Comoras' },
  { codigo: 'CG', nombre: 'Congo' },
  { codigo: 'KP', nombre: 'Corea del Norte' },
  { codigo: 'KR', nombre: 'Corea del Sur' },
  { codigo: 'CI', nombre: 'Costa de Marfil' },
  { codigo: 'CR', nombre: 'Costa Rica' },
  { codigo: 'HR', nombre: 'Croacia' },
  { codigo: 'CU', nombre: 'Cuba' },
  { codigo: 'CW', nombre: 'Curazao' },
  { codigo: 'DK', nombre: 'Dinamarca' },
  { codigo: 'DM', nombre: 'Dominica' },
  { codigo: 'EC', nombre: 'Ecuador' },
  { codigo: 'EG', nombre: 'Egipto' },
  { codigo: 'SV', nombre: 'El Salvador' },
  { codigo: 'AE', nombre: 'Emiratos Árabes Unidos' },
  { codigo: 'ER', nombre: 'Eritrea' },
  { codigo: 'SK', nombre: 'Eslovaquia' },
  { codigo: 'SI', nombre: 'Eslovenia' },
  { codigo: 'ES', nombre: 'España' },
  { codigo: 'FM', nombre: 'Estados Federados de Micronesia' },
  { codigo: 'US', nombre: 'Estados Unidos' },
  { codigo: 'EE', nombre: 'Estonia' },
  { codigo: 'ET', nombre: 'Etiopía' },
  { codigo: 'RU', nombre: 'Federación Rusa' },
  { codigo: 'PH', nombre: 'Filipinas' },
  { codigo: 'FI', nombre: 'Finlandia' },
  { codigo: 'FJ', nombre: 'Fiyi' },
  { codigo: 'FR', nombre: 'Francia' },
  { codigo: 'GA', nombre: 'Gabón' },
  { codigo: 'GM', nombre: 'Gambia' },
  { codigo: 'GE', nombre: 'Georgia' },
  { codigo: 'GH', nombre: 'Ghana' },
  { codigo: 'GI', nombre: 'Gibraltar' },
  { codigo: 'GD', nombre: 'Granada' },
  { codigo: 'GR', nombre: 'Grecia' },
  { codigo: 'GL', nombre: 'Groenlandia' },
  { codigo: 'GP', nombre: 'Guadalupe' },
  { codigo: 'GU', nombre: 'Guam' },
  { codigo: 'GT', nombre: 'Guatemala' },
  { codigo: 'GF', nombre: 'Guayana Francesa' },
  { codigo: 'GG', nombre: 'Guernsey' },
  { codigo: 'GN', nombre: 'Guinea' },
  { codigo: 'GQ', nombre: 'Guinea Ecuatorial' },
  { codigo: 'GW', nombre: 'Guinea-Bisáu' },
  { codigo: 'GY', nombre: 'Guyana' },
  { codigo: 'HT', nombre: 'Haití' },
  { codigo: 'HN', nombre: 'Honduras' },
  { codigo: 'HK', nombre: 'Hong Kong' },
  { codigo: 'HU', nombre: 'Hungría' },
  { codigo: 'IN', nombre: 'India' },
  { codigo: 'ID', nombre: 'Indonesia' },
  { codigo: 'IQ', nombre: 'Irak' },
  { codigo: 'IR', nombre: 'Irán (República Islámica de)' },
  { codigo: 'IE', nombre: 'Irlanda' },
  { codigo: 'BV', nombre: 'Isla Bouvet' },
  { codigo: 'IM', nombre: 'Isla de Man' },
  { codigo: 'CX', nombre: 'Isla de Navidad' },
  { codigo: 'NF', nombre: 'Isla Norfolk' },
  { codigo: 'IS', nombre: 'Islandia' },
  { codigo: 'KY', nombre: 'Islas Caimán' },
  { codigo: 'CC', nombre: 'Islas Cocos (Keeling)' },
  { codigo: 'CK', nombre: 'Islas Cook' },
  { codigo: 'FO', nombre: 'Islas Feroe' },
  { codigo: 'GS', nombre: 'Islas Georgias del Sur y Sándwich del Sur' },
  { codigo: 'HM', nombre: 'Islas Heard y McDonald' },
  { codigo: 'FK', nombre: 'Islas Malvinas (Falkland)' },
  { codigo: 'MP', nombre: 'Islas Marianas del Norte' },
  { codigo: 'MH', nombre: 'Islas Marshall' },
  { codigo: 'UM', nombre: 'Islas menores alejadas de EE. UU.' },
  { codigo: 'PN', nombre: 'Islas Pitcairn' },
  { codigo: 'SB', nombre: 'Islas Salomón' },
  { codigo: 'TC', nombre: 'Islas Turcas y Caicos' },
  { codigo: 'VG', nombre: 'Islas Vírgenes Británicas' },
  { codigo: 'VI', nombre: 'Islas Vírgenes de EE. UU.' },
  { codigo: 'IL', nombre: 'Israel' },
  { codigo: 'IT', nombre: 'Italia' },
  { codigo: 'JM', nombre: 'Jamaica' },
  { codigo: 'JP', nombre: 'Japón' },
  { codigo: 'JE', nombre: 'Jersey' },
  { codigo: 'JO', nombre: 'Jordania' },
  { codigo: 'KZ', nombre: 'Kazajistán' },
  { codigo: 'KE', nombre: 'Kenia' },
  { codigo: 'KG', nombre: 'Kirguistán' },
  { codigo: 'KI', nombre: 'Kiribati' },
  { codigo: 'XK', nombre: 'Kosovo' },
  { codigo: 'KW', nombre: 'Kuwait' },
  { codigo: 'LA', nombre: 'Laos' },
  { codigo: 'LS', nombre: 'Lesoto' },
  { codigo: 'LV', nombre: 'Letonia' },
  { codigo: 'LB', nombre: 'Líbano' },
  { codigo: 'LR', nombre: 'Liberia' },
  { codigo: 'LY', nombre: 'Libia' },
  { codigo: 'LI', nombre: 'Liechtenstein' },
  { codigo: 'LT', nombre: 'Lituania' },
  { codigo: 'LU', nombre: 'Luxemburgo' },
  { codigo: 'MO', nombre: 'Macao' },
  { codigo: 'MK', nombre: 'Macedonia del Norte' },
  { codigo: 'MG', nombre: 'Madagascar' },
  { codigo: 'MY', nombre: 'Malasia' },
  { codigo: 'MW', nombre: 'Malaui' },
  { codigo: 'MV', nombre: 'Maldivas' },
  { codigo: 'ML', nombre: 'Malí' },
  { codigo: 'MT', nombre: 'Malta' },
  { codigo: 'MA', nombre: 'Marruecos' },
  { codigo: 'MQ', nombre: 'Martinica' },
  { codigo: 'MU', nombre: 'Mauricio' },
  { codigo: 'MR', nombre: 'Mauritania' },
  { codigo: 'YT', nombre: 'Mayotte' },
  { codigo: 'MX', nombre: 'México' },
  { codigo: 'MC', nombre: 'Mónaco' },
  { codigo: 'MN', nombre: 'Mongolia' },
  { codigo: 'ME', nombre: 'Montenegro' },
  { codigo: 'MS', nombre: 'Montserrat' },
  { codigo: 'MZ', nombre: 'Mozambique' },
  { codigo: 'MM', nombre: 'Myanmar' },
  { codigo: 'NA', nombre: 'Namibia' },
  { codigo: 'NP', nombre: 'Nepal' },
  { codigo: 'NI', nombre: 'Nicaragua' },
  { codigo: 'NE', nombre: 'Níger' },
  { codigo: 'NG', nombre: 'Nigeria' },
  { codigo: 'NU', nombre: 'Niue' },
  { codigo: 'NO', nombre: 'Noruega' },
  { codigo: 'NC', nombre: 'Nueva Caledonia' },
  { codigo: 'NZ', nombre: 'Nueva Zelanda' },
  { codigo: 'OM', nombre: 'Omán' },
  { codigo: 'PD', nombre: 'País de prueba' },
  { codigo: 'NL', nombre: 'Países Bajos' },
  { codigo: 'PK', nombre: 'Pakistán' },
  { codigo: 'PW', nombre: 'Palaos' },
  { codigo: 'PA', nombre: 'Panamá' },
  { codigo: 'PG', nombre: 'Papúa Nueva Guinea' },
  { codigo: 'PY', nombre: 'Paraguay' },
  { codigo: 'PE', nombre: 'Perú' },
  { codigo: 'PF', nombre: 'Polinesia Francesa' },
  { codigo: 'PL', nombre: 'Polonia' },
  { codigo: 'PT', nombre: 'Portugal' },
  { codigo: 'PR', nombre: 'Puerto Rico' },
  { codigo: 'GB', nombre: 'Reino Unido' },
  { codigo: 'CF', nombre: 'República Centroafricana' },
  { codigo: 'CZ', nombre: 'República Checa' },
  { codigo: 'MD', nombre: 'República de Moldova' },
  { codigo: 'CD', nombre: 'República Democrática del Congo' },
  { codigo: 'DO', nombre: 'República Dominicana' },
  { codigo: 'RE', nombre: 'Reunión' },
  { codigo: 'RW', nombre: 'Ruanda' },
  { codigo: 'RO', nombre: 'Rumanía' },
  { codigo: 'EH', nombre: 'Sáhara Occidental' },
  { codigo: 'WS', nombre: 'Samoa' },
  { codigo: 'AS', nombre: 'Samoa Americana' },
  { codigo: 'KN', nombre: 'San Cristóbal y Nieves' },
  { codigo: 'SM', nombre: 'San Marino' },
  { codigo: 'MF', nombre: 'San Martín (parte francesa)' },
  { codigo: 'PM', nombre: 'San Pedro y Miquelón' },
  { codigo: 'VC', nombre: 'San Vicente y las Granadinas' },
  { codigo: 'SH', nombre: 'Santa Elena' },
  { codigo: 'LC', nombre: 'Santa Lucía' },
  { codigo: 'VA', nombre: 'Santa Sede (Ciudad del Vaticano)' },
  { codigo: 'ST', nombre: 'Santo Tomé y Príncipe' },
  { codigo: 'SN', nombre: 'Senegal' },
  { codigo: 'RS', nombre: 'Serbia' },
  { codigo: 'SC', nombre: 'Seychelles' },
  { codigo: 'SL', nombre: 'Sierra Leona' },
  { codigo: 'SG', nombre: 'Singapur' },
  { codigo: 'SX', nombre: 'Sint Maarten' },
  { codigo: 'SY', nombre: 'Siria' },
  { codigo: 'SO', nombre: 'Somalia' },
  { codigo: 'LK', nombre: 'Sri Lanka' },
  { codigo: 'SZ', nombre: 'Suazilandia (Esuatini)' },
  { codigo: 'ZA', nombre: 'Sudáfrica' },
  { codigo: 'SD', nombre: 'Sudán' },
  { codigo: 'SE', nombre: 'Suecia' },
  { codigo: 'CH', nombre: 'Suiza' },
  { codigo: 'SR', nombre: 'Surinam' },
  { codigo: 'SJ', nombre: 'Svalbard y Jan Mayen' },
  { codigo: 'TH', nombre: 'Tailandia' },
  { codigo: 'TW', nombre: 'Taiwán' },
  { codigo: 'TZ', nombre: 'Tanzania' },
  { codigo: 'TJ', nombre: 'Tayikistán' },
  { codigo: 'IO', nombre: 'Territorio Británico del Océano Índico' },
  { codigo: 'TF', nombre: 'Territorios Australes Franceses' },
  { codigo: 'PS', nombre: 'Territorios Palestinos' },
  { codigo: 'TP', nombre: 'Timor Oriental' },
  { codigo: 'TG', nombre: 'Togo' },
  { codigo: 'TK', nombre: 'Tokelau' },
  { codigo: 'TO', nombre: 'Tonga' },
  { codigo: 'TT', nombre: 'Trinidad y Tobago' },
  { codigo: 'TN', nombre: 'Túnez' },
  { codigo: 'TM', nombre: 'Turkmenistán' },
  { codigo: 'TR', nombre: 'Turquía' },
  { codigo: 'TV', nombre: 'Tuvalu' },
  { codigo: 'UA', nombre: 'Ucrania' },
  { codigo: 'UG', nombre: 'Uganda' },
  { codigo: 'UY', nombre: 'Uruguay' },
  { codigo: 'UZ', nombre: 'Uzbekistán' },
  { codigo: 'VU', nombre: 'Vanuatu' },
  { codigo: 'VE', nombre: 'Venezuela' },
  { codigo: 'VN', nombre: 'Vietnam' },
  { codigo: 'WF', nombre: 'Wallis y Futuna' },
  { codigo: 'YE', nombre: 'Yemen' },
  { codigo: 'DJ', nombre: 'Yibuti' },
  { codigo: 'YU', nombre: 'Yugoslavia' },
  { codigo: 'ZM', nombre: 'Zambia' },
  { codigo: 'ZW', nombre: 'Zimbabue' },
]

// Campos geográficos que SICVECA exige por actividad (clase_dato). Cada uno es un
// código de país de la tabla PAIS. Facilidades Crediticias (47) no lleva ninguno.
// key = columna en la tabla `transacciones`; label = etiqueta para el formulario.
export function getCamposGeograficos(claseDato) {
  const clase = Number(claseDato)
  const paisOrigen  = { key: 'pais_origen_recursos',  label: 'País origen de los recursos' }
  const paisDestino = { key: 'pais_destino_recursos', label: 'País destino de los recursos' }
  switch (clase) {
    case 42: // OSFL / ONG
      return [
        { key: 'ubicacion_cliente', label: 'Ubicación del donador (país)' },
        paisOrigen, paisDestino,
      ]
    case 44: // Administración de dinero
    case 46: // Emisión/operación de tarjetas
    case 48: // Servicios fiduciarios
      return [
        { key: 'ubicacion_cliente', label: 'Ubicación del cliente (país)' },
        paisOrigen, paisDestino,
      ]
    case 40: // Metales y piedras preciosas
    case 41: // Casas de empeño
    case 49: // Bienes inmuebles
      return [
        { key: 'ubicacion_comprador_vendedor', label: 'Ubicación comprador/vendedor (país)' },
        paisOrigen, paisDestino,
      ]
    case 43: // Casinos
      return [paisOrigen]
    case 45: // Remesas / transferencias
      return [
        { key: 'pais_origen_recursos',  label: 'País origen de la remesa' },
        { key: 'pais_destino_recursos', label: 'País destino de la remesa' },
      ]
    default: // 47 Facilidades Crediticias y otros → sin campos geográficos
      return []
  }
}
